//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.14 at 10:21:47 AM CEST 
//


package fl.routeGenerator.cosm;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fl.routeGenerator.cosm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AutoFeedUrl_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "auto_feed_url");
    private final static QName _Private_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "private");
    private final static QName _ItemsPerPage_QNAME = new QName("http://a9.com/-/spec/opensearch/1.1/", "itemsPerPage");
    private final static QName _Tag_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "tag");
    private final static QName _Status_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "status");
    private final static QName _Website_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "website");
    private final static QName _Feed_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "feed");
    private final static QName _MaxValue_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "max_value");
    private final static QName _MinValue_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "min_value");
    private final static QName _Title_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "title");
    private final static QName _StartIndex_QNAME = new QName("http://a9.com/-/spec/opensearch/1.1/", "startIndex");
    private final static QName _Description_QNAME = new QName("http://www.eeml.org/xsd/0.5.1", "description");
    private final static QName _TotalResults_QNAME = new QName("http://a9.com/-/spec/opensearch/1.1/", "totalResults");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fl.routeGenerator.cosm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Eeml }
     * 
     */
    public Eeml createEeml() {
        return new Eeml();
    }

    /**
     * Create an instance of {@link Environment }
     * 
     */
    public Environment createEnvironment() {
        return new Environment();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link CurrentValue }
     * 
     */
    public CurrentValue createCurrentValue() {
        return new CurrentValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "auto_feed_url")
    public JAXBElement<String> createAutoFeedUrl(String value) {
        return new JAXBElement<String>(_AutoFeedUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "private")
    public JAXBElement<Boolean> createPrivate(Boolean value) {
        return new JAXBElement<Boolean>(_Private_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "itemsPerPage")
    public JAXBElement<BigInteger> createItemsPerPage(BigInteger value) {
        return new JAXBElement<BigInteger>(_ItemsPerPage_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "tag")
    public JAXBElement<String> createTag(String value) {
        return new JAXBElement<String>(_Tag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "website")
    public JAXBElement<String> createWebsite(String value) {
        return new JAXBElement<String>(_Website_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "feed")
    public JAXBElement<String> createFeed(String value) {
        return new JAXBElement<String>(_Feed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "max_value")
    public JAXBElement<BigDecimal> createMaxValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MaxValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "min_value")
    public JAXBElement<BigDecimal> createMinValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MinValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "title")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "startIndex")
    public JAXBElement<BigInteger> createStartIndex(BigInteger value) {
        return new JAXBElement<BigInteger>(_StartIndex_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eeml.org/xsd/0.5.1", name = "description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "totalResults")
    public JAXBElement<BigInteger> createTotalResults(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalResults_QNAME, BigInteger.class, null, value);
    }

}
