//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.14 at 10:21:47 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eeml.org/xsd/0.5.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fl.routeGenerator.cosm;
